/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "inverse-surface": "#27313c",
          "secondary-container": "#8a4cfc",
          "surface": "#f7f9ff",
          "on-tertiary-fixed": "#2f1500",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-container": "#fffbff",
          "on-tertiary-fixed-variant": "#6e3900",
          "on-secondary-fixed-variant": "#5a00c6",
          "surface-variant": "#d9e3f2",
          "primary-fixed": "#85f8c4",
          "on-error-container": "#93000a",
          "inverse-primary": "#68dba9",
          "tertiary-fixed-dim": "#ffb77d",
          "tertiary": "#8d4b00",
          "on-secondary-container": "#fffbff",
          "primary-container": "#00855d",
          "tertiary-container": "#b15f00",
          "outline": "#6d7a72",
          "surface-container-highest": "#d9e3f2",
          "on-surface": "#121c27",
          "outline-variant": "#bccac0",
          "surface-bright": "#f7f9ff",
          "on-secondary": "#ffffff",
          "on-primary-container": "#f5fff7",
          "on-error": "#ffffff",
          "error": "#ba1a1a",
          "surface-dim": "#d1dbe9",
          "primary-fixed-dim": "#68dba9",
          "on-tertiary": "#ffffff",
          "error-container": "#ffdad6",
          "secondary-fixed-dim": "#d2bbff",
          "background": "#f7f9ff",
          "on-primary": "#ffffff",
          "on-secondary-fixed": "#25005a",
          "on-background": "#121c27",
          "inverse-on-surface": "#e8f1ff",
          "primary": "#006948",
          "surface-tint": "#006c4a",
          "on-surface-variant": "#3d4a42",
          "on-primary-fixed": "#002114",
          "surface-container-low": "#edf4ff",
          "secondary": "#712ae2",
          "on-primary-fixed-variant": "#005137",
          "surface-container": "#e5effd",
          "surface-container-high": "#dfe9f7",
          "secondary-fixed": "#eaddff",
          "tertiary-fixed": "#ffdcc3"
      },
      "fontFamily": {
          "sans": ["DM Sans", "sans-serif"],
          "mono": ["JetBrains Mono", "monospace"],
          "headline": ["DM Sans", "Manrope"],
          "body": ["DM Sans", "Manrope"],
          "label": ["JetBrains Mono", "Space Grotesk"]
      }
    },
  },
  plugins: [],
}
